name: Deploy to VPS

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Install SSH Key
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.SERVER_SSH_KEY }}
          known_hosts: ${{ secrets.KNOWN_HOSTS }}

      - name: Deploy to Server
        run: |
          ssh mahutt@trysqlite.com << EOF
            cd /var/www/trySQLite
            git pull origin main
            cd client
            npm install
            npm run build
            cd ../server
            go build main.go
            systemctl restart trysqlite-backend.service
          EOF
